version: '3.5'
services:
  wordfy-flask-api:
    image: wordfy-api
    container_name: wordfy-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:3000"
    volumes:
      - .:/app/
    environment:
      - PORT=80
